### PR TITLE
accept and passthrough timeout param to add_unit

### PR DESCRIPTION
**Pull request by dpb1**

### CODE REVIEW

**Comment by marcoceppi** [comment]
This feel an awful lot like #106 which we're waiting feedback on still from @johnsca if the proposed fixes there would work we should focus efforts on that instead

**Comment by dpb1** [comment]
Hi @marcoceppi any objections to merging this in now?  This allows more complicated add_units to succeed if the dev wishes.

**Comment by johnsca** [comment]
I didn't realize the other PR was waiting on me.  I'm somewhat against merging this, even though it's a simpler change, primarily because I don't want to add a parameter and then take it away again almost immediately.  I updated the other PR so we can hopefully get it resolved soon.

**Comment by ryan-beisner** [comment]
Is the timeout=300 default sane?  How is that to be overridden?  I know 5 min is not always enough time for our tests to add a unit.

**Comment by johnsca** [comment]
#106 is back to having merge conflicts and failing again, and is clearly a more invasive change, although I do think it fixes cases that aren't covered currently.

@ryan-beisner The 300s default value can be overridden when calling `add_unit`, e.g.:

```python
self.d.add_unit('foo', timeout=20*60)
```

This is the same as the current timeout, which cannot be overridden at all.  This change lets it be controlled by the test.

I'm ok with moving forward with this instead of #106 since it doesn't seem like the more complex change is compelling enough to warrant its complexity, given it hasn't been signed off on by now.

**Comment by arosales** [comment]
From what I can gather the current proposal is to merge this pull request, and close #106. If folks agree please +1.

**Comment by mbruzek** [comment]
Has this fix landed in an amulet release? I just got the following error:

```
DEBUG:runner:2016-09-01 14:45:56 Starting deployment of amazon
DEBUG:runner:2016-09-01 14:45:57 Deploying services...
DEBUG:runner:2016-09-01 14:45:58  Deploying service etcd using /tmp/charmdEsxAm/xenial/etcd
DEBUG:runner:2016-09-01 14:51:04 Adding relations...
DEBUG:runner:2016-09-01 14:51:05 Deployment complete in 309.69 seconds
DEBUG:runner:...E
DEBUG:runner:======================================================================
DEBUG:runner:ERROR: test_node_scale (__main__.TestDeployment)
DEBUG:runner:Scale beyond 1 node because etcd supports peering as a standalone
DEBUG:runner:----------------------------------------------------------------------
DEBUG:runner:Traceback (most recent call last):
DEBUG:runner:  File "/tmp/tmpkMpIcu/etcd/tests/10-deploy", line 31, in test_node_scale
DEBUG:runner:    self.d.add_unit('etcd', timeout=1200)
DEBUG:runner:TypeError: add_unit() got an unexpected keyword argument 'timeout'
```

**Comment by marcoceppi** [comment]
@mbruzek have you tried 1.16.0?

**Pull request merged**
